---
# roles: cluster_admin, cluster_view, teamlead, developer
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      k8s_context:  "xanis-admin@xanis.local"
      k8s_config: "~/.kube/config"
#
#      users:
#        - name: b-eslamifar
#          role: cluster_view
#          namespaces: []
#
#        - name: s-rezaei
#          role: teamlead
#          namespaces:
#            - test
#            - test2

#      namespaces:
#        - name: test
#          quota:
#            request_ephemeral_storage: "1Gi"
#            limit_ephemeral_storage: "2Gi"
#            loadbalancer_limit: "0"
#            request_cpu:
#            request_memory:
#            limit_cpu:
#            limit_memory:
#            configmaps_limit:
#            pvc_limit:
#            pods_limit:    
#            replicationcontroller_limit:
#            resource_quota_limit:
#            service_limit:
#            nodport_limit:
