apiVersion: v1
data:
  userID: <base64_encoded_userid>
  userKey: <base64_encoded_key>
kind: Secret
metadata:
  name: test-csi-rbd-secret
  namespace: ceph-csi
type: Opaque

---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-csi
mountOptions:
- discard
parameters:
  clusterID: 0b23f638-58d5-11eb-8d5c-08002734328e
  csi.storage.k8s.io/controller-expand-secret-name: test-csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi
  csi.storage.k8s.io/controller-publish-secret-name: test-csi-rbd-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: ceph-csi
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-publish-secret-name: test-csi-rbd-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ceph-csi
  csi.storage.k8s.io/node-stage-secret-name: test-csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi
  csi.storage.k8s.io/provisioner-secret-name: test-csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi
  imageFeatures: layering
  pool: <pool_name>
  volumeNamePrefix: csi-vol-
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

