---
- name: User | Create service account
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ item.name }}"
        namespace: users
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
  with_items:
    - "{{ users }}"

- name: User | Apply clusterrolebindig
  k8s:
    state: present
    definition: "{{lookup('template', 'templates/clusterrolebinding.yml.j2') | from_yaml}}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
  with_items:
    - "{{ users }}"
  register: clusterrole
  when: item.role == 'cluster_view' or item.role == 'cluster_admin'

- name: User | Apply rolebinding
  k8s:
    state: present
    definition: "{{lookup('template', 'templates/rolebinding.yml.j2') | from_yaml}}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
  with_subelements:
    - "{{ users }}"
    - namespaces
  when: item.0.role != 'cluster_view' and item.0.role != 'cluster_admin'

