---
# roles: cluster_admin, cluster_view, teamlead, developer
all:
  hosts:
    localhost:
      ansible_connection: local
#     users:
#       - user: b-eslamifar
#         role: cluster_view
#
#       - user: a-asghari
#         role: teamlead
#         namespaces:
#           - test
#           - test2

#     namespaces:
#       - name: test
#         quota:
#           request_ephemeral_storage: 
#           limit_ephemeral_storage:
#           loadbalancer_limit:
#           request_cpu:
#           request_memory:
#           limit_cpu:
#           limit_memory:
#           configmaps_limit:
#           pvc_limit:
#           pods_limit:    
#           replicationcontroller_limit:
#           resource_quota_limit:
#           service_limit:
#           nodport_limit:
